# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'

networks:
  docker:
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  vaccineslotfinder-postgresql:
    image: postgres:13.2
    # volumes:
    #   - ~/volumes/jhipster/vaccineSlotFinder/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=vaccineSlotFinder
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 5432:5432
    networks:
      docker:
        ipv4_address: 172.20.0.6
